### ISSUE TITLE
incorrect version numbers

### ISSUE THREAD

**Issue by rmetzler** [TelekomLabs/cloudinit#1]
https://github.com/TelekomLabs/cloudinit/blob/master/templates/chef/cloudinit_ps1.moustache#L13-L15

http://www.heise.de/security/news/foren/S-Re-Wow-wie-kreativ-Noch-nicht-einmal-den-Code-angeschaut-und-schon-dumme-Witz/forum-290777/msg-26353857/read/

**Comment by chris-rock** [comment]
thanks @rmetzler version 0.2.4 uses the latest version of chef 12
